### ISSUE TITLE
What about drupal.js?

### ISSUE THREAD

**Issue by binki** [mikl/node-drupal#7]
Is there an npm package that attempts to implement drupal.js, e.g. `Drupal.behaviors`? This module looks like server-side stuff. If there’s information about the client-side drupal.js, could the README be updated to point people interested in that to the right place?

Thanks.

**Comment by mikl** [comment]
Not to my knowledge. Not sure why you'd want that, either, since it's very tied to Drupal itself.

**Comment by mikl** [comment]
Feel free to reopen this if you find something.
